/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaVersC */

#ifndef _Included_JavaVersC
#define _Included_JavaVersC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaVersC
 * Method:    bonjour
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaVersC_bonjour
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
