# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/tp5

FORMS += facture.ui 
HEADERS += facturemodel.h \
           factureimpl.h \
           factureview.h \
           mywidget.h 
SOURCES += tp5.cpp \
           facturemodel.cpp \
           factureimpl.cpp \
           factureview.cpp 
TARGET=../bin/tp5
