(bateau vrai)
(voiles  vrai)
(de-croisiere  vrai)
(nombre-de-mats=1 faux)
(moteur vrai)
(un-mat faux)
;(voilier)
;(mat-d-artimon-inferieur-a-mat-d-avant vrai)
;(trois-coques faux)
;(deux-coques vrai)
;(est-habitable vrai)
;(plaisance vrai)