# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/calc

HEADERS += CalcGUI.h \
           Controller.h 
SOURCES += calc.cpp \
           CalcGUI.cpp \
           Controller.cpp 
TARGET = ../bin/calc
CONFIG += release \
warn_on \
qt \
x11
TEMPLATE = app
